---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: default_metrics
  metrics_path: "/api/v1/metrics"
  static_configs:
  - targets: ["server:4788"]
- job_name: custom_metrics
  metrics_path: "/api/v1/metrics/custom"
  static_configs:
  - targets: ["server:4788"]