{
 "title": "Custom Metrics",
 "time": { "from": "2023-04-25T20:07:28.086Z", "to": "2023-04-25T20:07:30.382Z" },
 "panels": [
  {
   "title": "Latency /hello/:name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/hello/:name\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/hello/:name\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/hello/:name\"}[1m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/hello/:name\"}[1m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency /pokemon/:id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/pokemon/:id\"}[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/pokemon/:id\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/pokemon/:id\"}[1m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(api_v1_request_duration_seconds_bucket{endpoint=\"/pokemon/:id\"}[1m])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "api_v1_request_duration_seconds_count{status=\"200\"}",
     "legendFormat": "Success {{endpoint}}"
    },
    {
     "expr": "api_v1_request_duration_seconds_count{status!=\"200\"}",
     "legendFormat": "Failures {{endpoint}}"
    }
   ]
  }
 ]
}