---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: server_v1
  metrics_path: "/api/v1/metrics"
  static_configs:
  - targets: ["server:4788"]