version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: > # able to do multiple lines of commands with && or any symbol
      sh -c "/target-executable"
    ports:
      - "${SERVER_PORT:-4599}:${SERVER_PORT:-4599}"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      #environment variables, if not present :- default
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
