version: "3.9"

services:
  api_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: > # able to do multiple lines of commands with && or any symbol
      sh -c "/target-executable"
    ports:
      - "${SERVER_PORT:-4599}:${SERVER_PORT:-4599}"
      - "${MONITORING_PORT:-4788}:${MONITORING_PORT:-4788}"
    env_file:
      - .env
    depends_on:
      - db_service
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./api/networking/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api_service
  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-devops123}
    volumes:
      - ./api/networking/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./api/networking/monitoring/grafana/dashboards/provisioning/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./api/networking/monitoring/grafana/dashboards/dashboards:/var/lib/grafana/dashboards
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
  db_service:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  prometheus:
  grafana:
  postgres_data:
