version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: > # able to do multiple lines of commands with && or any symbol
      sh -c "/target-executable"
    ports:
      - "${SERVER_PORT:-4599}:${SERVER_PORT:-4599}"
      - "${MONITORING_PORT:-4788}:${MONITORING_PORT:-4788}"
    env_file:
      - .env
    depends_on:
      - db
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./api/networking/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - ./api/networking/monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      #environment variables, if not present :- default
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  grafana:
  postgres_data:
