version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: > # able to do multiple lines of commands with && or any symbol
      sh -c "/target-executable"
    ports:
      - "${SERVER_PORT:-4599}:${SERVER_PORT:-4599}"
      - "${MONITORING_PORT:-4788}:${MONITORING_PORT:-4788}"
    env_file:
      - .env
    depends_on:
      - db
  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    volumes:
      - ./api/router/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - server
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      #environment variables, if not present :- default
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
