apiVersion: v1
kind: Pod
metadata:
  name: api_pod
  labels:
    app: api_server
spec:
  containers:
  - name: api_container
    image: api_image:latest
    ports:
      - containerPort: ${SERVER_PORT:-4599}
        name: http-api
      - containerPort: ${MONITORING_PORT:-4788}
        name: http-metrics
---
apiVersion: v1
kind: Deployment
metadata:
  name: api_deployment
  labels:
    app: api_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_server
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: api_service
spec:
  type: ClusterIP
  selector:
    app: api_server
  ports:
    - name: http-api
      appProtocol: http
      protocol: TCP
      port: http-api
    - name: http-metrics
      appProtocol: http
      protocol: TCP
      port: http-metrics
---
